/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IInstadappLiteInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "viewStinstaTokens"
      | "viewStinstaTokensValue"
      | "withdrawStinstaTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "viewStinstaTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "viewStinstaTokensValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStinstaTokens",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "viewStinstaTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewStinstaTokensValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStinstaTokens",
    data: BytesLike
  ): Result;
}

export interface IInstadappLite extends BaseContract {
  connect(runner?: ContractRunner | null): IInstadappLite;
  waitForDeployment(): Promise<this>;

  interface: IInstadappLiteInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  viewStinstaTokens: TypedContractMethod<
    [stinstaAmount: BigNumberish],
    [bigint],
    "view"
  >;

  viewStinstaTokensValue: TypedContractMethod<
    [mstValue: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawStinstaTokens: TypedContractMethod<
    [assets_: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "viewStinstaTokens"
  ): TypedContractMethod<[stinstaAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "viewStinstaTokensValue"
  ): TypedContractMethod<[mstValue: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawStinstaTokens"
  ): TypedContractMethod<[assets_: BigNumberish], [bigint], "nonpayable">;

  filters: {};
}
