/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EnderPreLounchDepositInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "bondableTokens"
      | "bonds"
      | "claimRebaseReward"
      | "deposit"
      | "depositEnable"
      | "index"
      | "initialize"
      | "isWhitelisted"
      | "lido"
      | "minDepositAmount"
      | "owner"
      | "renounceOwnership"
      | "rewardShareIndex"
      | "rewardSharePerUserIndexStEth"
      | "setAddress"
      | "setBondableTokens"
      | "setDepositEnable"
      | "setMinDepAmount"
      | "stEth"
      | "totalRewardOfUser"
      | "totalStaked"
      | "transferOwnership"
      | "whitelist"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BondableTokensSet"
      | "Deposit"
      | "Initialized"
      | "MinDepAmountSet"
      | "OwnershipTransferred"
      | "WhitelistChanged"
      | "depositEnableSet"
      | "userInfo"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bondableTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "bonds", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "claimRebaseReward",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositEnable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "index", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lido", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minDepositAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardShareIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardSharePerUserIndexStEth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBondableTokens",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositEnable",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinDepAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stEth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalRewardOfUser",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bondableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bonds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRebaseReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositEnable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "index", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lido", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minDepositAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardShareIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardSharePerUserIndexStEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBondableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositEnable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinDepAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stEth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRewardOfUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
}

export namespace BondableTokensSetEvent {
  export type InputTuple = [token: AddressLike, isEnabled: boolean];
  export type OutputTuple = [token: string, isEnabled: boolean];
  export interface OutputObject {
    token: string;
    isEnabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    sender: AddressLike,
    index: BigNumberish,
    bondFees: BigNumberish,
    principal: BigNumberish,
    maturity: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    index: bigint,
    bondFees: bigint,
    principal: bigint,
    maturity: bigint,
    token: string
  ];
  export interface OutputObject {
    sender: string;
    index: bigint;
    bondFees: bigint;
    principal: bigint;
    maturity: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinDepAmountSetEvent {
  export type InputTuple = [newAmount: BigNumberish];
  export type OutputTuple = [newAmount: bigint];
  export interface OutputObject {
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistChangedEvent {
  export type InputTuple = [whitelistingAddress: AddressLike, action: boolean];
  export type OutputTuple = [whitelistingAddress: string, action: boolean];
  export interface OutputObject {
    whitelistingAddress: string;
    action: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace depositEnableSetEvent {
  export type InputTuple = [depositEnable: boolean];
  export type OutputTuple = [depositEnable: boolean];
  export interface OutputObject {
    depositEnable: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace userInfoEvent {
  export type InputTuple = [
    user: AddressLike,
    index: BigNumberish,
    principal: BigNumberish,
    Reward: BigNumberish,
    totalAmount: BigNumberish,
    bondFees: BigNumberish,
    maturity: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    index: bigint,
    principal: bigint,
    Reward: bigint,
    totalAmount: bigint,
    bondFees: bigint,
    maturity: bigint
  ];
  export interface OutputObject {
    user: string;
    index: bigint;
    principal: bigint;
    Reward: bigint;
    totalAmount: bigint;
    bondFees: bigint;
    maturity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EnderPreLounchDeposit extends BaseContract {
  connect(runner?: ContractRunner | null): EnderPreLounchDeposit;
  waitForDeployment(): Promise<this>;

  interface: EnderPreLounchDepositInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  bondableTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  bonds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        user: string;
        principalAmount: bigint;
        totalAmount: bigint;
        bondFees: bigint;
        maturity: bigint;
      }
    ],
    "view"
  >;

  claimRebaseReward: TypedContractMethod<
    [index: BigNumberish, _bond: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        user: string;
        principal: bigint;
        bonfees: bigint;
        maturity: bigint;
      }
    ],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [
      principal: BigNumberish,
      maturity: BigNumberish,
      bondFee: BigNumberish,
      token: AddressLike
    ],
    [void],
    "payable"
  >;

  depositEnable: TypedContractMethod<[], [boolean], "view">;

  index: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [_stEth: AddressLike, _lido: AddressLike],
    [void],
    "nonpayable"
  >;

  isWhitelisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lido: TypedContractMethod<[], [string], "view">;

  minDepositAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardShareIndex: TypedContractMethod<[], [bigint], "view">;

  rewardSharePerUserIndexStEth: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  setAddress: TypedContractMethod<
    [_addr: AddressLike, _type: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBondableTokens: TypedContractMethod<
    [tokens: AddressLike[], enabled: boolean],
    [void],
    "nonpayable"
  >;

  setDepositEnable: TypedContractMethod<
    [_depositEnable: boolean],
    [void],
    "nonpayable"
  >;

  setMinDepAmount: TypedContractMethod<
    [_amt: BigNumberish],
    [void],
    "nonpayable"
  >;

  stEth: TypedContractMethod<[], [string], "view">;

  totalRewardOfUser: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  whitelist: TypedContractMethod<
    [_whitelistingAddress: AddressLike, _action: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bondableTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "bonds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        user: string;
        principalAmount: bigint;
        totalAmount: bigint;
        bondFees: bigint;
        maturity: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimRebaseReward"
  ): TypedContractMethod<
    [index: BigNumberish, _bond: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        user: string;
        principal: bigint;
        bonfees: bigint;
        maturity: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      principal: BigNumberish,
      maturity: BigNumberish,
      bondFee: BigNumberish,
      token: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositEnable"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "index"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_stEth: AddressLike, _lido: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lido"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "minDepositAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardShareIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardSharePerUserIndexStEth"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAddress"
  ): TypedContractMethod<
    [_addr: AddressLike, _type: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBondableTokens"
  ): TypedContractMethod<
    [tokens: AddressLike[], enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDepositEnable"
  ): TypedContractMethod<[_depositEnable: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinDepAmount"
  ): TypedContractMethod<[_amt: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stEth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalRewardOfUser"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<
    [_whitelistingAddress: AddressLike, _action: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BondableTokensSet"
  ): TypedContractEvent<
    BondableTokensSetEvent.InputTuple,
    BondableTokensSetEvent.OutputTuple,
    BondableTokensSetEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MinDepAmountSet"
  ): TypedContractEvent<
    MinDepAmountSetEvent.InputTuple,
    MinDepAmountSetEvent.OutputTuple,
    MinDepAmountSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistChanged"
  ): TypedContractEvent<
    WhitelistChangedEvent.InputTuple,
    WhitelistChangedEvent.OutputTuple,
    WhitelistChangedEvent.OutputObject
  >;
  getEvent(
    key: "depositEnableSet"
  ): TypedContractEvent<
    depositEnableSetEvent.InputTuple,
    depositEnableSetEvent.OutputTuple,
    depositEnableSetEvent.OutputObject
  >;
  getEvent(
    key: "userInfo"
  ): TypedContractEvent<
    userInfoEvent.InputTuple,
    userInfoEvent.OutputTuple,
    userInfoEvent.OutputObject
  >;

  filters: {
    "BondableTokensSet(address,bool)": TypedContractEvent<
      BondableTokensSetEvent.InputTuple,
      BondableTokensSetEvent.OutputTuple,
      BondableTokensSetEvent.OutputObject
    >;
    BondableTokensSet: TypedContractEvent<
      BondableTokensSetEvent.InputTuple,
      BondableTokensSetEvent.OutputTuple,
      BondableTokensSetEvent.OutputObject
    >;

    "Deposit(address,uint256,uint256,uint256,uint256,address)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MinDepAmountSet(uint256)": TypedContractEvent<
      MinDepAmountSetEvent.InputTuple,
      MinDepAmountSetEvent.OutputTuple,
      MinDepAmountSetEvent.OutputObject
    >;
    MinDepAmountSet: TypedContractEvent<
      MinDepAmountSetEvent.InputTuple,
      MinDepAmountSetEvent.OutputTuple,
      MinDepAmountSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WhitelistChanged(address,bool)": TypedContractEvent<
      WhitelistChangedEvent.InputTuple,
      WhitelistChangedEvent.OutputTuple,
      WhitelistChangedEvent.OutputObject
    >;
    WhitelistChanged: TypedContractEvent<
      WhitelistChangedEvent.InputTuple,
      WhitelistChangedEvent.OutputTuple,
      WhitelistChangedEvent.OutputObject
    >;

    "depositEnableSet(bool)": TypedContractEvent<
      depositEnableSetEvent.InputTuple,
      depositEnableSetEvent.OutputTuple,
      depositEnableSetEvent.OutputObject
    >;
    depositEnableSet: TypedContractEvent<
      depositEnableSetEvent.InputTuple,
      depositEnableSetEvent.OutputTuple,
      depositEnableSetEvent.OutputObject
    >;

    "userInfo(address,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      userInfoEvent.InputTuple,
      userInfoEvent.OutputTuple,
      userInfoEvent.OutputObject
    >;
    userInfo: TypedContractEvent<
      userInfoEvent.InputTuple,
      userInfoEvent.OutputTuple,
      userInfoEvent.OutputObject
    >;
  };
}
