/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStrategy,
  IStrategyInterface,
} from "../../../../../contracts/strategy/eigenlayer/EnderELStrategy.sol/IStrategy";

const _abi = [
  {
    inputs: [],
    name: "maxTotalDeposits",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IStrategyInterface {
    return new Interface(_abi) as IStrategyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IStrategy {
    return new Contract(address, _abi, runner) as unknown as IStrategy;
  }
}
